/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103453-g4de4bc06fd-20210830"
#endif /* AVUTIL_FFVERSION_H */
