/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103420-g1da524121c-20210828"
#endif /* AVUTIL_FFVERSION_H */
