# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/UI/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1154, 732)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mw_icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color:  rgb(251, 251, 251);\n"
"}")
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(5, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.main_frame.setFont(font)
        self.main_frame.setStyleSheet("background-color: rgb(50, 63, 75);\n"
"border-radius: 5px;")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.inside_frame = QtWidgets.QFrame(self.main_frame)
        self.inside_frame.setGeometry(QtCore.QRect(20, 20, 441, 571))
        self.inside_frame.setStyleSheet("    background-color: rgb(31, 41, 51);\n"
"    border-radius: 5px;")
        self.inside_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inside_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inside_frame.setObjectName("inside_frame")
        self.main_logo_text = QtWidgets.QLabel(self.inside_frame)
        self.main_logo_text.setGeometry(QtCore.QRect(25, 20, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Heavy CAPS")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.main_logo_text.setFont(font)
        self.main_logo_text.setStyleSheet("color: rgb(154, 165, 177)")
        self.main_logo_text.setObjectName("main_logo_text")
        self.download_button_2 = QtWidgets.QPushButton(self.inside_frame)
        self.download_button_2.setGeometry(QtCore.QRect(20, 520, 61, 30))
        self.download_button_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(31, 41, 51)\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 190, 255);\n"
"    border: 2px solid rgb(50, 190, 255);\n"
"}\n"
"")
        self.download_button_2.setObjectName("download_button_2")
        self.file_options_frame = QtWidgets.QFrame(self.inside_frame)
        self.file_options_frame.setGeometry(QtCore.QRect(20, 320, 141, 91))
        self.file_options_frame.setStyleSheet("    background-color: rgb(82, 96, 109);\n"
"    border-radius: 5px;")
        self.file_options_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.file_options_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.file_options_frame.setObjectName("file_options_frame")
        self.mp3_radio_button = QtWidgets.QRadioButton(self.file_options_frame)
        self.mp3_radio_button.setGeometry(QtCore.QRect(9, 32, 96, 21))
        self.mp3_radio_button.setStyleSheet("QRadioButton::indicator {\n"
"    border: 3px solid rgb(62, 76, 89);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(50, 63, 75);\n"
"}\n"
"\n"
"QRadioButton { \n"
"    color: rgb(154, 165, 177)\n"
"\n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(62, 76, 89);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(50, 63, 75);    \n"
"}")
        self.mp3_radio_button.setObjectName("mp3_radio_button")
        self.mp4_radio_button = QtWidgets.QRadioButton(self.file_options_frame)
        self.mp4_radio_button.setGeometry(QtCore.QRect(9, 61, 96, 21))
        self.mp4_radio_button.setStyleSheet("QRadioButton::indicator {\n"
"    border: 3px solid rgb(62, 76, 89);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(50, 63, 75);\n"
"}\n"
"\n"
"QRadioButton { \n"
"    color: rgb(154, 165, 177)\n"
"\n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(62, 76, 89);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(50, 63, 75);    \n"
"}")
        self.mp4_radio_button.setChecked(True)
        self.mp4_radio_button.setObjectName("mp4_radio_button")
        self.file_options_text = QtWidgets.QLabel(self.file_options_frame)
        self.file_options_text.setGeometry(QtCore.QRect(10, 6, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.file_options_text.setFont(font)
        self.file_options_text.setStyleSheet("color: rgb(154, 165, 177)")
        self.file_options_text.setObjectName("file_options_text")
        self.coming_soon_frame = QtWidgets.QFrame(self.file_options_frame)
        self.coming_soon_frame.setGeometry(QtCore.QRect(0, 0, 141, 91))
        self.coming_soon_frame.setStyleSheet("    background-color: rgba(82, 96, 109, 100);\n"
"    border-radius: 5px;")
        self.coming_soon_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.coming_soon_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.coming_soon_frame.setObjectName("coming_soon_frame")
        self.coming_soon_text = QtWidgets.QLabel(self.coming_soon_frame)
        self.coming_soon_text.setGeometry(QtCore.QRect(20, 35, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.coming_soon_text.setFont(font)
        self.coming_soon_text.setStyleSheet("color: rgb(154, 165, 177)")
        self.coming_soon_text.setObjectName("coming_soon_text")
        self.video_quality_frame = QtWidgets.QFrame(self.inside_frame)
        self.video_quality_frame.setGeometry(QtCore.QRect(170, 320, 251, 91))
        self.video_quality_frame.setStyleSheet("    background-color: rgb(82, 96, 109);\n"
"    border-radius: 5px;")
        self.video_quality_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.video_quality_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.video_quality_frame.setObjectName("video_quality_frame")
        self.video_quality_text = QtWidgets.QLabel(self.video_quality_frame)
        self.video_quality_text.setGeometry(QtCore.QRect(10, 6, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.video_quality_text.setFont(font)
        self.video_quality_text.setStyleSheet("color: rgb(154, 165, 177)")
        self.video_quality_text.setObjectName("video_quality_text")
        self.video_quality_selctor_frame = QtWidgets.QFrame(self.video_quality_frame)
        self.video_quality_selctor_frame.setGeometry(QtCore.QRect(10, 30, 225, 51))
        self.video_quality_selctor_frame.setStyleSheet("    background-color: rgb(62, 76, 89);\n"
"    border-radius: 5px;")
        self.video_quality_selctor_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.video_quality_selctor_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.video_quality_selctor_frame.setObjectName("video_quality_selctor_frame")
        self.button_240p = QtWidgets.QPushButton(self.video_quality_selctor_frame)
        self.button_240p.setGeometry(QtCore.QRect(5, 4, 40, 42))
        self.button_240p.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(82, 96, 109);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(82, 96, 109);\n"
"    color: rgb(154, 165, 177)\n"
"}\n"
"")
        self.button_240p.setObjectName("button_240p")
        self.button_360p = QtWidgets.QPushButton(self.video_quality_selctor_frame)
        self.button_360p.setGeometry(QtCore.QRect(49, 4, 40, 42))
        self.button_360p.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(82, 96, 109);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(82, 96, 109);\n"
"    color: rgb(154, 165, 177)\n"
"}\n"
"")
        self.button_360p.setObjectName("button_360p")
        self.button_480p = QtWidgets.QPushButton(self.video_quality_selctor_frame)
        self.button_480p.setGeometry(QtCore.QRect(93, 4, 40, 42))
        self.button_480p.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(82, 96, 109);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(82, 96, 109);\n"
"    color: rgb(154, 165, 177)\n"
"}\n"
"")
        self.button_480p.setObjectName("button_480p")
        self.button_720p = QtWidgets.QPushButton(self.video_quality_selctor_frame)
        self.button_720p.setGeometry(QtCore.QRect(137, 4, 40, 42))
        self.button_720p.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(82, 96, 109);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(82, 96, 109);\n"
"    color: rgb(154, 165, 177)\n"
"}\n"
"")
        self.button_720p.setObjectName("button_720p")
        self.button_1080p = QtWidgets.QPushButton(self.video_quality_selctor_frame)
        self.button_1080p.setGeometry(QtCore.QRect(181, 4, 40, 42))
        self.button_1080p.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(82, 96, 109);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(82, 96, 109);\n"
"    color: rgb(154, 165, 177)\n"
"}\n"
"")
        self.button_1080p.setObjectName("button_1080p")
        self.video_quality_highlighter_frame = QtWidgets.QFrame(self.video_quality_selctor_frame)
        self.video_quality_highlighter_frame.setGeometry(QtCore.QRect(48, 4, 40, 42))
        self.video_quality_highlighter_frame.setStyleSheet("background-color: rgba(154, 165, 177, 100);")
        self.video_quality_highlighter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.video_quality_highlighter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.video_quality_highlighter_frame.setObjectName("video_quality_highlighter_frame")
        self.disable_background_frame = QtWidgets.QFrame(self.video_quality_frame)
        self.disable_background_frame.setGeometry(QtCore.QRect(-160, -350, 481, 611))
        self.disable_background_frame.setStyleSheet("    background-color: rgba(31, 41, 51, 150);\n"
"    border-radius: 5px;")
        self.disable_background_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.disable_background_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.disable_background_frame.setObjectName("disable_background_frame")
        self.error_frame = QtWidgets.QFrame(self.disable_background_frame)
        self.error_frame.setEnabled(True)
        self.error_frame.setGeometry(QtCore.QRect(80, 190, 321, 101))
        self.error_frame.setStyleSheet("    background-color: rgb(62, 76, 89);\n"
"    border-radius: 5px;")
        self.error_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.error_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.error_frame.setObjectName("error_frame")
        self.pytube_error_text = QtWidgets.QLabel(self.error_frame)
        self.pytube_error_text.setGeometry(QtCore.QRect(10, 10, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pytube_error_text.setFont(font)
        self.pytube_error_text.setStyleSheet("color: rgb(154, 165, 177)")
        self.pytube_error_text.setObjectName("pytube_error_text")
        self.error_message_line_edit = QtWidgets.QLineEdit(self.error_frame)
        self.error_message_line_edit.setEnabled(False)
        self.error_message_line_edit.setGeometry(QtCore.QRect(20, 40, 281, 31))
        self.error_message_line_edit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.error_message_line_edit.setFont(font)
        self.error_message_line_edit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.error_message_line_edit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(82, 96, 109);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(82, 96, 109);\n"
"    padding-left: 10px;\n"
"    color: rgb(154, 165, 177)\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(50, 63, 75);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(50, 63, 75);\n"
"}")
        self.error_message_line_edit.setText("")
        self.error_message_line_edit.setObjectName("error_message_line_edit")
        self.close_error_frame_button = QtWidgets.QPushButton(self.error_frame)
        self.close_error_frame_button.setGeometry(QtCore.QRect(290, 6, 25, 25))
        self.close_error_frame_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(82, 96, 109);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(82, 96, 109);\n"
"    color: rgb(154, 165, 177)\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 0, 0);\n"
"    border: 2px solid rgb(200, 0, 0);\n"
"}\n"
"")
        self.close_error_frame_button.setText("")
        icon1 = QtGui.QIcon()
        import os
        if os.name == 'nt':
                icon1.addPixmap(QtGui.QPixmap("Resources/UI\\../../../YoutubeDownloader-main/icons/24x24/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        elif os.name == 'posix':
                icon1.addPixmap(QtGui.QPixmap("Resources/UI/../../../YoutubeDownloader-main/icons/24x24/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_error_frame_button.setIcon(icon1)
        self.close_error_frame_button.setIconSize(QtCore.QSize(16, 16))
        self.close_error_frame_button.setObjectName("close_error_frame_button")
        self.downloading_frame = QtWidgets.QFrame(self.disable_background_frame)
        self.downloading_frame.setEnabled(True)
        self.downloading_frame.setGeometry(QtCore.QRect(90, 370, 321, 101))
        self.downloading_frame.setStyleSheet("    background-color: rgb(62, 76, 89);\n"
"    border-radius: 5px;")
        self.downloading_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.downloading_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.downloading_frame.setObjectName("downloading_frame")
        self.downloading_video_text = QtWidgets.QLabel(self.downloading_frame)
        self.downloading_video_text.setGeometry(QtCore.QRect(10, 10, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.downloading_video_text.setFont(font)
        self.downloading_video_text.setStyleSheet("color: rgb(154, 165, 177)")
        self.downloading_video_text.setObjectName("downloading_video_text")
        self.video_downloading_progress_bar = QtWidgets.QProgressBar(self.downloading_frame)
        self.video_downloading_progress_bar.setGeometry(QtCore.QRect(30, 50, 261, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.video_downloading_progress_bar.setFont(font)
        self.video_downloading_progress_bar.setStyleSheet("QProgressBar {\n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(31, 41, 51);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.693, x2:1, y2:0.75, stop:0 rgb(131, 201, 255), stop:1 rgba(229, 49, 255, 255))\n"
"}")
        self.video_downloading_progress_bar.setProperty("value", 0)
        self.video_downloading_progress_bar.setObjectName("video_downloading_progress_bar")
        self.video_save_path_frame = QtWidgets.QFrame(self.inside_frame)
        self.video_save_path_frame.setGeometry(QtCore.QRect(20, 420, 401, 80))
        self.video_save_path_frame.setStyleSheet("    background-color:rgb(62, 76, 89);\n"
"    border-radius: 5px;")
        self.video_save_path_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.video_save_path_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.video_save_path_frame.setObjectName("video_save_path_frame")
        self.file_location_line_edit = QtWidgets.QLineEdit(self.video_save_path_frame)
        self.file_location_line_edit.setEnabled(False)
        self.file_location_line_edit.setGeometry(QtCore.QRect(110, 40, 281, 30))
        self.file_location_line_edit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.file_location_line_edit.setFont(font)
        self.file_location_line_edit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.file_location_line_edit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(82, 96, 109);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(82, 96, 109);\n"
"    padding-left: 10px;\n"
"    color: rgb(154, 165, 177)\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(50, 63, 75);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(50, 63, 75);\n"
"}")
        self.file_location_line_edit.setText("")
        self.file_location_line_edit.setObjectName("file_location_line_edit")
        self.save_path_button = QtWidgets.QPushButton(self.video_save_path_frame)
        self.save_path_button.setGeometry(QtCore.QRect(10, 40, 91, 30))
        self.save_path_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(82, 96, 109);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(82, 96, 109);\n"
"    color: rgb(154, 165, 177)\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(97, 110, 124);\n"
"    border: 2px solid rgb(97, 110, 124);\n"
"}\n"
"")
        self.save_path_button.setObjectName("save_path_button")
        self.video_save_path_text = QtWidgets.QLabel(self.video_save_path_frame)
        self.video_save_path_text.setGeometry(QtCore.QRect(8, 6, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.video_save_path_text.setFont(font)
        self.video_save_path_text.setStyleSheet("color: rgb(154, 165, 177)")
        self.video_save_path_text.setObjectName("video_save_path_text")
        self.video_preview_frame = QtWidgets.QFrame(self.inside_frame)
        self.video_preview_frame.setGeometry(QtCore.QRect(100, 160, 240, 130))
        self.video_preview_frame.setStyleSheet("    background-color:rgb(62, 76, 89);\n"
"    border-radius: 5px;")
        self.video_preview_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.video_preview_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.video_preview_frame.setObjectName("video_preview_frame")
        self.video_title_text = QtWidgets.QLabel(self.video_preview_frame)
        self.video_title_text.setGeometry(QtCore.QRect(10, 10, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.video_title_text.setFont(font)
        self.video_title_text.setStyleSheet("color: rgb(154, 165, 177)")
        self.video_title_text.setObjectName("video_title_text")
        self.video_author_text = QtWidgets.QLabel(self.video_preview_frame)
        self.video_author_text.setGeometry(QtCore.QRect(10, 30, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.video_author_text.setFont(font)
        self.video_author_text.setStyleSheet("color: rgb(154, 165, 177)")
        self.video_author_text.setObjectName("video_author_text")
        self.views_button_icon = QtWidgets.QPushButton(self.video_preview_frame)
        self.views_button_icon.setEnabled(False)
        self.views_button_icon.setGeometry(QtCore.QRect(0, 95, 41, 30))
        self.views_button_icon.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(62, 76, 89);\n"
"    color: rgb(154, 165, 177)\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(97, 110, 124);\n"
"    border: 2px solid rgb(97, 110, 124);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(170, 0, 170);\n"
"    border: 2px solid rgb(170, 0, 170);\n"
"}")
        self.views_button_icon.setText("")
        icon2 = QtGui.QIcon()
        import os
        if os.name == 'nt':
                icon2.addPixmap(QtGui.QPixmap("Resources/UI\\../../../YoutubeDownloader-main/icons/24x24/cil-people.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        elif os.name == 'posix':
                icon2.addPixmap(QtGui.QPixmap("Resources/UI/../../../YoutubeDownloader-main/icons/24x24/cil-people.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.views_button_icon.setIcon(icon2)
        self.views_button_icon.setObjectName("views_button_icon")
        self.views_text = QtWidgets.QLabel(self.video_preview_frame)
        self.views_text.setGeometry(QtCore.QRect(33, 102, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.views_text.setFont(font)
        self.views_text.setStyleSheet("color: rgb(154, 165, 177)")
        self.views_text.setObjectName("views_text")
        self.refresh_video_preview_button = QtWidgets.QPushButton(self.video_preview_frame)
        self.refresh_video_preview_button.setGeometry(QtCore.QRect(200, 90, 31, 30))
        self.refresh_video_preview_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(82, 96, 109);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(82, 96, 109);\n"
"    color: rgb(154, 165, 177)\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(97, 110, 124);\n"
"    border: 2px solid rgb(97, 110, 124);\n"
"}\n"
"")
        self.refresh_video_preview_button.setText("")
        icon3 = QtGui.QIcon()

        import os
        if os.name == 'nt':
                icon3.addPixmap(QtGui.QPixmap("Resources/UI\\../../../YoutubeDownloader-main/icons/24x24/cil-loop-circular.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        elif os.name == 'posix':
                icon3.addPixmap(QtGui.QPixmap("Resources/UI/../../../YoutubeDownloader-main/icons/24x24/cil-loop-circular.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.refresh_video_preview_button.setIcon(icon3)
        self.refresh_video_preview_button.setObjectName("refresh_video_preview_button")
        self.video_link_line_edit = QtWidgets.QLineEdit(self.inside_frame)
        self.video_link_line_edit.setGeometry(QtCore.QRect(20, 100, 401, 30))
        self.video_link_line_edit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.video_link_line_edit.setFont(font)
        self.video_link_line_edit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.video_link_line_edit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(82, 96, 109);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(82, 96, 109);\n"
"    padding-left: 10px;\n"
"    color: rgb(154, 165, 177)\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(50, 63, 75);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(50, 63, 75);\n"
"}")
        self.video_link_line_edit.setText("")
        self.video_link_line_edit.setObjectName("video_link_line_edit")
        self.close_button = QtWidgets.QPushButton(self.main_frame)
        self.close_button.setGeometry(QtCore.QRect(446, 9, 25, 25))
        self.close_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(180, 0, 0);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(180, 0, 0);\n"
"    color: rgb(154, 165, 177)\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 0, 0);\n"
"    border: 2px solid rgb(200, 0, 0);\n"
"}\n"
"")
        self.close_button.setText("")
        self.close_button.setIcon(icon1)
        self.close_button.setIconSize(QtCore.QSize(16, 16))
        self.close_button.setObjectName("close_button")
        self.verticalLayout.addWidget(self.main_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.youtube_tab = QtWidgets.QPushButton(self.centralwidget)
        self.youtube_tab.setMinimumSize(QtCore.QSize(120, 40))
        self.youtube_tab.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        self.youtube_tab.setFont(font)
        self.youtube_tab.setStyleSheet("QPushButton{\n"
"color: #282828;\n"
"border: None;\n"
"border-radius: 5px;\n"
"background-color: rgb(251, 251, 251);\n"
"}\n"
"QPushButton::hover{\n"
"border: None;\n"
"background-color: rgb(234, 234, 234);\n"
"}\n"
"QPushButton::checked{\n"
"border: None;\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton::pressed{\n"
"border: None;\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/mw_icons/youtube_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.youtube_tab.setIcon(icon4)
        self.youtube_tab.setIconSize(QtCore.QSize(28, 28))
        self.youtube_tab.setCheckable(True)
        self.youtube_tab.setChecked(True)
        self.youtube_tab.setAutoRepeat(False)
        self.youtube_tab.setDefault(False)
        self.youtube_tab.setObjectName("youtube_tab")
        self.bg = QtWidgets.QButtonGroup(MainWindow)
        self.bg.setObjectName("bg")
        self.bg.addButton(self.youtube_tab)
        self.verticalLayout.addWidget(self.youtube_tab)
        self.downloads_tab = QtWidgets.QPushButton(self.centralwidget)
        self.downloads_tab.setMinimumSize(QtCore.QSize(120, 40))
        self.downloads_tab.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        self.downloads_tab.setFont(font)
        self.downloads_tab.setStyleSheet("QPushButton{\n"
"border: None;\n"
"border-radius: 5px;\n"
"background-color: rgb(251, 251, 251);\n"
"}\n"
"QPushButton::hover{\n"
"border: None;\n"
"background-color: rgb(234, 234, 234);\n"
"}\n"
"QPushButton::checked{\n"
"border: None;\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton::pressed{\n"
"border: None;\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/mw_icons/downloads_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.downloads_tab.setIcon(icon5)
        self.downloads_tab.setIconSize(QtCore.QSize(26, 26))
        self.downloads_tab.setCheckable(True)
        self.downloads_tab.setObjectName("downloads_tab")
        self.bg.addButton(self.downloads_tab)
        self.verticalLayout.addWidget(self.downloads_tab)
        self.settings_tab = QtWidgets.QPushButton(self.centralwidget)
        self.settings_tab.setMinimumSize(QtCore.QSize(120, 40))
        self.settings_tab.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        self.settings_tab.setFont(font)
        self.settings_tab.setStyleSheet("QPushButton{\n"
"border: None;\n"
"border-radius: 5px;\n"
"background-color: rgb(251, 251, 251);\n"
"}\n"
"QPushButton::hover{\n"
"border: None;\n"
"background-color: rgb(234, 234, 234);\n"
"}\n"
"QPushButton::checked{\n"
"border: None;\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton::pressed{\n"
"border: None;\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/mw_icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.settings_tab.setIcon(icon6)
        self.settings_tab.setIconSize(QtCore.QSize(26, 26))
        self.settings_tab.setCheckable(True)
        self.settings_tab.setObjectName("settings_tab")
        self.bg.addButton(self.settings_tab)
        self.verticalLayout.addWidget(self.settings_tab)
        spacerItem1 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabw = QtWidgets.QTabWidget(self.centralwidget)
        self.tabw.setStyleSheet("QTabBar::tab {\n"
" border: none;\n"
"background: transparent;\n"
"color: rgb(251, 251, 251);\n"
"max-height: 0px;\n"
"}\n"
"QTabWidget::pane {\n"
"\n"
"   border-left: 1px solid rgb(230, 230, 230);\n"
"}")
        self.tabw.setTabBarAutoHide(False)
        self.tabw.setObjectName("tabw")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_4.setMinimumSize(QtCore.QSize(35, 28))
        self.pushButton_4.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: 1px solid #59CDF2;\n"
"border-right:None;\n"
"border-bottom-left-radius:5px;\n"
"border-top-left-radius:5px;\n"
"}")
        self.pushButton_4.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/mw_icons/link_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_4.setIcon(icon7)
        self.pushButton_4.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.youtube_link = QtWidgets.QLineEdit(self.tab_1)
        self.youtube_link.setMinimumSize(QtCore.QSize(0, 28))
        self.youtube_link.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        self.youtube_link.setFont(font)
        self.youtube_link.setStyleSheet("\n"
"QLineEdit{\n"
"background-color: white;\n"
"border: 1px solid #59CDF2;\n"
"border-left: None;\n"
"border-right: None;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border: 1px solid #29e1ff;\n"
"border-left: none;\n"
"border-right: none;\n"
"}")
        self.youtube_link.setClearButtonEnabled(True)
        self.youtube_link.setObjectName("youtube_link")
        self.horizontalLayout_4.addWidget(self.youtube_link)
        self.link_direct_2 = QtWidgets.QPushButton(self.tab_1)
        self.link_direct_2.setMinimumSize(QtCore.QSize(35, 28))
        self.link_direct_2.setMaximumSize(QtCore.QSize(35, 16777215))
        self.link_direct_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.link_direct_2.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: 1px solid #59CDF2;\n"
"border-left:None;\n"
"border-bottom-right-radius:5px;\n"
"border-top-right-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(234, 234, 234);\n"
"border: 1px solid #59CDF2;\n"
"border-left:None;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(225, 225, 225);\n"
"border: 1px solid #59CDF2;\n"
"border-left:None;\n"
"}")
        self.link_direct_2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/mw_icons/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.link_direct_2.setIcon(icon8)
        self.link_direct_2.setIconSize(QtCore.QSize(18, 18))
        self.link_direct_2.setObjectName("link_direct_2")
        self.horizontalLayout_4.addWidget(self.link_direct_2)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.link_direct = QtWidgets.QPushButton(self.tab_1)
        self.link_direct.setMinimumSize(QtCore.QSize(35, 28))
        self.link_direct.setMaximumSize(QtCore.QSize(35, 16777215))
        self.link_direct.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.link_direct.setStyleSheet("QPushButton{\n"
"background: none;\n"
"border: None;\n"
"border-radius: 6px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 170, 255, 30);\n"
"border: None;\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgba(0, 170, 255, 40);\n"
"border: None;\n"
"}")
        self.link_direct.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/mw_icons/downward_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.link_direct.setIcon(icon9)
        self.link_direct.setIconSize(QtCore.QSize(22, 22))
        self.link_direct.setObjectName("link_direct")
        self.horizontalLayout_4.addWidget(self.link_direct)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_3.setStyleSheet("background: transparent;\n"
"border: None;")
        self.pushButton_3.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/mw_icons/video_frames.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_3.setIcon(icon10)
        self.pushButton_3.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #282828;")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.frame = QtWidgets.QFrame(self.tab_1)
        self.frame.setStyleSheet("border: 1px solid rgb(200, 200, 200);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.browser = QtWebEngineWidgets.QWebEngineView(self.frame)
        self.browser.setStyleSheet("border: None;")
        self.browser.setObjectName("browser")
        self.gridLayout_2.addWidget(self.browser, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.web_back = QtWidgets.QPushButton(self.tab_1)
        self.web_back.setMinimumSize(QtCore.QSize(30, 30))
        self.web_back.setStyleSheet("QPushButton{\n"
"background: none;\n"
"border: None;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 170, 255, 30);\n"
"border: None;\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgba(0, 170, 255, 40);\n"
"border: None;\n"
"}")
        self.web_back.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/mw_icons/back_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.web_back.setIcon(icon11)
        self.web_back.setIconSize(QtCore.QSize(28, 28))
        self.web_back.setObjectName("web_back")
        self.horizontalLayout_5.addWidget(self.web_back)
        self.web_home = QtWidgets.QPushButton(self.tab_1)
        self.web_home.setMinimumSize(QtCore.QSize(30, 30))
        self.web_home.setStyleSheet("QPushButton{\n"
"background: none;\n"
"border: None;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 170, 255, 30);\n"
"border: None;\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgba(0, 170, 255, 40);\n"
"border: None;\n"
"}")
        self.web_home.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/mw_icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.web_home.setIcon(icon12)
        self.web_home.setIconSize(QtCore.QSize(22, 22))
        self.web_home.setObjectName("web_home")
        self.horizontalLayout_5.addWidget(self.web_home)
        self.web_forward = QtWidgets.QPushButton(self.tab_1)
        self.web_forward.setMinimumSize(QtCore.QSize(30, 30))
        self.web_forward.setStyleSheet("QPushButton{\n"
"background: none;\n"
"border: None;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 170, 255, 30);\n"
"border: None;\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgba(0, 170, 255, 40);\n"
"border: None;\n"
"}")
        self.web_forward.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/mw_icons/right_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.web_forward.setIcon(icon13)
        self.web_forward.setIconSize(QtCore.QSize(28, 28))
        self.web_forward.setObjectName("web_forward")
        self.horizontalLayout_5.addWidget(self.web_forward)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.download_button = QtWidgets.QPushButton(self.tab_1)
        self.download_button.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        self.download_button.setFont(font)
        self.download_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.download_button.setStyleSheet("QPushButton {\n"
"background-color: DodgerBlue;\n"
"  border: none;\n"
"border-radius: 8px;\n"
"  color: white;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: RoyalBlue;\n"
"}\n"
"")
        self.download_button.setIconSize(QtCore.QSize(32, 32))
        self.download_button.setObjectName("download_button")
        self.horizontalLayout_5.addWidget(self.download_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabw.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setContentsMargins(0, 8, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(25)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem6 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.only_video = QtWidgets.QPushButton(self.tab_2)
        self.only_video.setMinimumSize(QtCore.QSize(45, 35))
        self.only_video.setMaximumSize(QtCore.QSize(45, 35))
        self.only_video.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: 1px solid #59CDF2;\n"
"border-right:None;\n"
"border-bottom-left-radius:6px;\n"
"border-top-left-radius:6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(234, 234, 234);\n"
"}\n"
"QPushButton:checked{\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(225, 225, 225);\n"
"}")
        self.only_video.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/mw_icons/video_format.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.only_video.setIcon(icon14)
        self.only_video.setIconSize(QtCore.QSize(22, 22))
        self.only_video.setCheckable(True)
        self.only_video.setObjectName("only_video")
        self.bg2 = QtWidgets.QButtonGroup(MainWindow)
        self.bg2.setObjectName("bg2")
        self.bg2.addButton(self.only_video)
        self.horizontalLayout_10.addWidget(self.only_video)
        self.video_audio = QtWidgets.QPushButton(self.tab_2)
        self.video_audio.setMinimumSize(QtCore.QSize(45, 35))
        self.video_audio.setMaximumSize(QtCore.QSize(45, 35))
        self.video_audio.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: 1px solid #59CDF2;\n"
"border-right:None;\n"
"border-left:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(234, 234, 234);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton:checked{\n"
"background-color: rgb(225, 225, 225);\n"
"}")
        self.video_audio.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/mw_icons/a_vs_v.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.video_audio.setIcon(icon15)
        self.video_audio.setIconSize(QtCore.QSize(32, 32))
        self.video_audio.setCheckable(True)
        self.video_audio.setChecked(True)
        self.video_audio.setObjectName("video_audio")
        self.bg2.addButton(self.video_audio)
        self.horizontalLayout_10.addWidget(self.video_audio)
        self.only_audio = QtWidgets.QPushButton(self.tab_2)
        self.only_audio.setMinimumSize(QtCore.QSize(45, 35))
        self.only_audio.setMaximumSize(QtCore.QSize(45, 35))
        self.only_audio.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: 1px solid #59CDF2;\n"
"border-left:None;\n"
"border-bottom-right-radius:6px;\n"
"border-top-right-radius:6px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(234, 234, 234);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton:checked{\n"
"background-color: rgb(225, 225, 225);\n"
"}")
        self.only_audio.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/mw_icons/audio_format.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.only_audio.setIcon(icon16)
        self.only_audio.setIconSize(QtCore.QSize(22, 22))
        self.only_audio.setCheckable(True)
        self.only_audio.setObjectName("only_audio")
        self.bg2.addButton(self.only_audio)
        self.horizontalLayout_10.addWidget(self.only_audio)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        spacerItem7 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.play = QtWidgets.QPushButton(self.tab_2)
        self.play.setMinimumSize(QtCore.QSize(30, 30))
        self.play.setStyleSheet("QPushButton{\n"
"background: none;\n"
"border: None;\n"
"border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 170, 255, 30);\n"
"border: None;\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgba(0, 170, 255, 40);\n"
"border: None;\n"
"}")
        self.play.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/mw_icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.play.setIcon(icon17)
        self.play.setIconSize(QtCore.QSize(32, 32))
        self.play.setObjectName("play")
        self.horizontalLayout_11.addWidget(self.play)
        self.open_in_folder = QtWidgets.QPushButton(self.tab_2)
        self.open_in_folder.setMinimumSize(QtCore.QSize(30, 30))
        self.open_in_folder.setStyleSheet("QPushButton{\n"
"background: none;\n"
"border: None;\n"
"border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 170, 255, 30);\n"
"border: None;\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgba(0, 170, 255, 40);\n"
"border: None;\n"
"}")
        self.open_in_folder.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/mw_icons/open_file_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.open_in_folder.setIcon(icon18)
        self.open_in_folder.setIconSize(QtCore.QSize(32, 32))
        self.open_in_folder.setObjectName("open_in_folder")
        self.horizontalLayout_11.addWidget(self.open_in_folder)
        self.remove = QtWidgets.QPushButton(self.tab_2)
        self.remove.setMinimumSize(QtCore.QSize(30, 30))
        self.remove.setStyleSheet("QPushButton{\n"
"background: none;\n"
"border: None;\n"
"border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 170, 255, 30);\n"
"border: None;\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgba(0, 170, 255, 40);\n"
"border: None;\n"
"}")
        self.remove.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/mw_icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.remove.setIcon(icon19)
        self.remove.setIconSize(QtCore.QSize(31, 31))
        self.remove.setObjectName("remove")
        self.horizontalLayout_11.addWidget(self.remove)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.tw = QtWidgets.QTableWidget(self.tab_2)
        self.tw.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tw.setFont(font)
        self.tw.setMouseTracking(False)
        self.tw.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tw.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tw.setAutoFillBackground(False)
        self.tw.setStyleSheet("\n"
"\n"
"QHeaderView::section {\n"
"background-color: #A2DBFA;\n"
"border: 1px solid rgb(210, 210, 210);\n"
"border-bottom: black; \n"
"border-bottom: 1px solid rgb(165, 165, 165);\n"
"} \n"
"QTableWidget::item:selected\n"
"{\n"
"background-color: rgba(0, 170, 255, 50);\n"
"}\n"
"")
        self.tw.setFrameShape(QtWidgets.QFrame.Panel)
        self.tw.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tw.setProperty("showDropIndicator", True)
        self.tw.setDragEnabled(False)
        self.tw.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tw.setAlternatingRowColors(False)
        self.tw.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tw.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tw.setTextElideMode(QtCore.Qt.ElideNone)
        self.tw.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tw.setShowGrid(True)
        self.tw.setGridStyle(QtCore.Qt.SolidLine)
        self.tw.setWordWrap(True)
        self.tw.setCornerButtonEnabled(False)
        self.tw.setRowCount(0)
        self.tw.setObjectName("tw")
        self.tw.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tw.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        self.tw.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        self.tw.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        self.tw.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        self.tw.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        self.tw.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        item.setFont(font)
        self.tw.setHorizontalHeaderItem(7, item)
        self.tw.horizontalHeader().setHighlightSections(False)
        self.tw.horizontalHeader().setMinimumSectionSize(39)
        self.tw.horizontalHeader().setStretchLastSection(False)
        self.tw.verticalHeader().setVisible(False)
        self.tw.verticalHeader().setDefaultSectionSize(30)
        self.tw.verticalHeader().setSortIndicatorShown(False)
        self.tw.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_6.addWidget(self.tw)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabw.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(20, 467, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem9, 2, 2, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(25)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        spacerItem10 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.default_path = QtWidgets.QLineEdit(self.tab_3)
        self.default_path.setMinimumSize(QtCore.QSize(0, 30))
        self.default_path.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(13)
        self.default_path.setFont(font)
        self.default_path.setStyleSheet("\n"
"QLineEdit{\n"
"background-color: white;\n"
"border: 1px solid #59CDF2;\n"
"border-right: None;\n"
"border-bottom-left-radius:3px;\n"
"border-top-left-radius:3px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border: 1px solid #29e1ff;\n"
"border-right: none;\n"
"}")
        self.default_path.setText("")
        self.default_path.setReadOnly(True)
        self.default_path.setObjectName("default_path")
        self.horizontalLayout_6.addWidget(self.default_path)
        self.open_folder = QtWidgets.QPushButton(self.tab_3)
        self.open_folder.setMinimumSize(QtCore.QSize(30, 30))
        self.open_folder.setMaximumSize(QtCore.QSize(16777215, 30))
        self.open_folder.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: 1px solid #59CDF2;\n"
"border-left:None;\n"
"border-bottom-right-radius:5px;\n"
"border-top-right-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(234, 234, 234);\n"
"border: 1px solid #59CDF2;\n"
"border-left:None;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(225, 225, 225);\n"
"border: 1px solid #59CDF2;\n"
"border-left:None;\n"
"}")
        self.open_folder.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/mw_icons/open_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.open_folder.setIcon(icon20)
        self.open_folder.setIconSize(QtCore.QSize(22, 22))
        self.open_folder.setObjectName("open_folder")
        self.horizontalLayout_6.addWidget(self.open_folder)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        spacerItem11 = QtWidgets.QSpacerItem(27, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.languages = QtWidgets.QComboBox(self.tab_3)
        self.languages.setMinimumSize(QtCore.QSize(160, 28))
        self.languages.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(13)
        font.setKerning(True)
        self.languages.setFont(font)
        self.languages.setStyleSheet("QComboBox {\n"
"    border: 1px solid #7cd0ef;\n"
"    border-radius: 5px;\n"
"}\n"
"QComboBox:hover{\n"
"border-color: #5487ee;\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
" \n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox::down-arrow {\n"
"  image: url(:/mw_icons/drop_down.png);\n"
"height: 18px;\n"
"width: 18px;\n"
"}\n"
"QComboBox::drop-down:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d8d7d7, stop: 1 #e9e9e9);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.languages.setIconSize(QtCore.QSize(22, 22))
        self.languages.setDuplicatesEnabled(False)
        self.languages.setObjectName("languages")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/mw_icons/uzbek.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.languages.addItem(icon21, "")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/mw_icons/russian.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.languages.addItem(icon22, "")
        self.horizontalLayout_8.addWidget(self.languages)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.feedback = QtWidgets.QPushButton(self.tab_3)
        self.feedback.setMinimumSize(QtCore.QSize(100, 28))
        self.feedback.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        self.feedback.setFont(font)
        self.feedback.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.feedback.setStyleSheet("QPushButton{\n"
"background: none;\n"
"border: None;\n"
"border-radius: 6px;\n"
"background: rgba(0, 170, 255, 30);\n"
"}\n"
"QPushButton:hover{\n"
"background: rgba(0, 170, 255, 60);\n"
"border: None;\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgba(0, 170, 255, 80);\n"
"border: None;\n"
"}")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/mw_icons/feedback.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.feedback.setIcon(icon23)
        self.feedback.setIconSize(QtCore.QSize(24, 24))
        self.feedback.setObjectName("feedback")
        self.horizontalLayout_9.addWidget(self.feedback)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.about = QtWidgets.QPushButton(self.tab_3)
        self.about.setMinimumSize(QtCore.QSize(200, 28))
        self.about.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        self.about.setFont(font)
        self.about.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.about.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border-radius: 6px;\n"
"border: 1px solid #6AF2F0;\n"
"}\n"
"QPushButton:hover {\n"
"color: white;\n"
"background-color: #6AF2F0;\n"
"}\n"
"QPushButton:pressed {\n"
"color: white;\n"
"background-color: rgb(47, 231, 247);\n"
"border: 1px solid rgb(42, 215, 218);\n"
"}\n"
"")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/mw_icons/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.about.setIcon(icon24)
        self.about.setIconSize(QtCore.QSize(22, 22))
        self.about.setObjectName("about")
        self.horizontalLayout_9.addWidget(self.about)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 1, 1, 1, 2)
        spacerItem13 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 1, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem14, 0, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem15, 1, 3, 1, 1)
        self.tabw.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tabw)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1154, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/mw_icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionExit.setIcon(icon25)
        self.actionExit.setObjectName("actionExit")
        self.exit = QtWidgets.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/mw_icons/close_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.exit.setIcon(icon26)
        self.exit.setObjectName("exit")
        self.menuFile.addAction(self.exit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabw.setCurrentIndex(0)
        self.link_direct_2.clicked.connect(self.youtube_link.paste)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YouTube DM"))
        self.main_logo_text.setText(_translate("MainWindow", "VIDEO DOWNLOADER"))
        self.download_button_2.setText(_translate("MainWindow", "Go!"))
        self.mp3_radio_button.setText(_translate("MainWindow", "Mp3"))
        self.mp4_radio_button.setText(_translate("MainWindow", "Mp4"))
        self.file_options_text.setText(_translate("MainWindow", "FILE OPTIONS"))
        self.coming_soon_text.setText(_translate("MainWindow", "COMING SOON!"))
        self.video_quality_text.setText(_translate("MainWindow", "VIDEO QUALITY"))
        self.button_240p.setText(_translate("MainWindow", "240p"))
        self.button_360p.setText(_translate("MainWindow", "360p"))
        self.button_480p.setText(_translate("MainWindow", "480p"))
        self.button_720p.setText(_translate("MainWindow", "720p"))
        self.button_1080p.setText(_translate("MainWindow", "1080p"))
        self.pytube_error_text.setText(_translate("MainWindow", "PYTUBE ERROR!"))
        self.error_message_line_edit.setPlaceholderText(_translate("MainWindow", "Error Message "))
        self.downloading_video_text.setText(_translate("MainWindow", "DOWNLOADING VIDEO..."))
        self.file_location_line_edit.setPlaceholderText(_translate("MainWindow", "File Location"))
        self.save_path_button.setText(_translate("MainWindow", "Save Path"))
        self.video_save_path_text.setText(_translate("MainWindow", "VIDEO SAVE PATH"))
        self.video_title_text.setText(_translate("MainWindow", "Video Title - Preview"))
        self.video_author_text.setText(_translate("MainWindow", "Author: "))
        self.views_text.setText(_translate("MainWindow", "1234"))
        self.video_link_line_edit.setPlaceholderText(_translate("MainWindow", "Video Link"))
        self.youtube_tab.setText(_translate("MainWindow", "YouTube"))
        self.downloads_tab.setText(_translate("MainWindow", "Yuklamalar"))
        self.settings_tab.setText(_translate("MainWindow", "Sozlamalar"))
        self.youtube_link.setPlaceholderText(_translate("MainWindow", "https://youtube.com"))
        self.label.setText(_translate("MainWindow", "YouTube"))
        self.download_button.setText(_translate("MainWindow", "Yuklash"))
        self.tw.setSortingEnabled(False)
        item = self.tw.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tw.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "path"))
        item = self.tw.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nomi"))
        item = self.tw.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Hajmi"))
        item = self.tw.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Davomiyligi"))
        item = self.tw.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Turi"))
        item = self.tw.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Formati"))
        item = self.tw.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Sanasi"))
        self.tabw.setTabText(self.tabw.indexOf(self.tab_2), _translate("MainWindow", "Page"))
        self.label_2.setText(_translate("MainWindow", "Saqlash manzili"))
        self.label_4.setText(_translate("MainWindow", "Dastur tili"))
        self.languages.setCurrentText(_translate("MainWindow", "O\'zbekcha"))
        self.languages.setItemText(0, _translate("MainWindow", "O\'zbekcha"))
        self.languages.setItemText(1, _translate("MainWindow", "Русский"))
        self.feedback.setText(_translate("MainWindow", "Aloqa"))
        self.about.setText(_translate("MainWindow", "Haqida"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.exit.setText(_translate("MainWindow", "Exit"))
from PyQt5 import QtWebEngineWidgets
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
